{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc6ad778",
   "metadata": {},
   "outputs": [],
   "source": [
    "from flask import flask, render_template, request, redirect, url_for, session, flash\n",
    "from flask_sqlalchemy import SQLALCHEMY\n",
    "from datetime import datetime\n",
    "\n",
    "app = Flask(_name_)\n",
    "app.secret_key = \"secret_key_for_session\"\n",
    "app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite://blog.db'\n",
    "db = SQLAlchemy(app)\n",
    "\n",
    "class User(db.Model):\n",
    "    id = db.Column(db.Integer, primary_key=TRUE)\n",
    "    username = db.Column(db.String(50), unique=True, nullable=False)\n",
    "    password = db.Column(db.String(50), nullable=False)\n",
    "\n",
    "class Post(db.Model):\n",
    "    id = db.Column(db.Integer, primary_key=True)\n",
    "    title = db.Column(db.String(200), nullable=False)\n",
    "    content = db.Column(db.Text, nullable=False)\n",
    "    date_posted = db.Column(db.DateTime, default=datetime.utcnow)\n",
    "    author = db.Column(db.String(100))\n",
    "    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))\n",
    "    \n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    posts = Post.query.order_by(Post.date_posted.desc()).all()\n",
    "    return render_template('index.html', posts=posts)\n",
    "\n",
    "@app.route('/post/<int:id>')\n",
    "def view_post(id):\n",
    "    post = Post.query.get_or_404(id)\n",
    "    return render_template('view_post.html', post=post)\n",
    "\n",
    "@app.route('/login', methods=['GET', 'POST'])\n",
    "def login():\n",
    "    if request.method == 'POST':\n",
    "        username = request.form['username']\n",
    "        password = request.form['password'] \n",
    "        user = User.query.filter_by(username=username, password=password).first()\n",
    "        \n",
    "        if user:\n",
    "            session['user_id'] = user.id\n",
    "            session['username'] = user.username\n",
    "            return redirect(url_for('dashboard'))\n",
    "        else:\n",
    "            flash(\"Invalid login credentials.\")\n",
    "        \n",
    "        return render_template('login.html')\n",
    "\n",
    "@app.route('/dashboard')\n",
    "def dashboard():\n",
    "    if 'user_id' not in session:\n",
    "        return redirect(url_for('login'))\n",
    "    \n",
    "    user_posts = Post.query.filter_by(user_id=session['user_id']).all()\n",
    "    return render_template('dashboard.html', post=user_posts)\n",
    "\n",
    "@app.route('/new', methods=['GET', 'POST'])\n",
    "def new_post():\n",
    "    if 'user_id' not in session:\n",
    "        return redirect(url_for('login'))\n",
    "    \n",
    "    if request.method =='POST':\n",
    "        title = request.form['title']\n",
    "        content = request.form['content']\n",
    "        author = session['username']\n",
    "        \n",
    "        new_post = Post(title=title, content=content, author=author, user_id=session['user_id'])\n",
    "        \n",
    "        db.session.add(new_post)\n",
    "        db.session.commit()\n",
    "        \n",
    "        flash(\"Post created successfully!\")\n",
    "        return redirect(url_for('dashboard'))\n",
    "    \n",
    "    return render_template('new_post.html')\n",
    "\n",
    "@app.route('/edit/<int:id>', methods=['GET', 'POST'])\n",
    "def edit_post(id):\n",
    "    post = Post.query.get_or_404(id)\n",
    "    \n",
    "    if 'user_id' not in session or post.user_id !=session['user_id']:\n",
    "        return redirect(url_for('login'))\n",
    "    \n",
    "    if request.method == 'POST':\n",
    "        post.title = request.form['title']\n",
    "        post.content = request.form['content']\n",
    "        db.session.commit()\n",
    "        flash(\"Post updated!\")\n",
    "        return redirect(url_for('dashboard'))\n",
    "    \n",
    "    return render_template('edit_post.html', post=post)\n",
    "\n",
    "@app.route('/delete/<int:id>')\n",
    "def delete_post(id):\n",
    "    post = Post.query.get_or_404(id)\n",
    "    \n",
    "    if 'user_id' not in session or post.user_id != session['user_id']:\n",
    "        return redirect(url_for('login'))\n",
    "    \n",
    "    db.session.delete(post)\n",
    "    db.session.commit()\n",
    "    flash(\"Post deleted\")\n",
    "    return redirect(url_for('dashboard'))\n",
    "\n",
    "if_name_=='_main_':\n",
    "    db.create_all()\n",
    "    app.run(debug=True)\n",
    "                            "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
